language: ruby
rvm:
    - 2.2.2
    - 2.3.0

gemfile:
    - Gemfile
    - gemfiles/activesupport4.2.x.gemfile
    - gemfiles/activesupport3.2.x.gemfile

script: time ./script/travis.sh

branches:
    only: master

sudo: required
dist: precise
group: legacy

# activesupport 4.0.0 only supported on ruby >= 1.9.3
