language: ruby
rvm:
    - 1.9.3
    - 2.0.0
    - 2.2.1
    - jruby-19mode

gemfile:
    - Gemfile
    - gemfiles/activesupport3.2.x.gemfile

script: time ./script/travis.sh

branches:
    only: master

# activesupport 4.0.0 only supported on ruby >= 1.9.3
